name: flutter_messaging_papercups
description: Flutter implementation of the papercups.io chat widget, built with a webview and provides customization options. 
version: 0.0.1-alpha
homepage: https://github.com/aguilaair/papercups_flutter
publish_to: none

environment:
  sdk: ">=2.16.0-55.0.dev <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_messaging_base: 
    git:  'https://github.com/phr34k/flutter_messaging_base.git'
  phoenix_socket: ^0.5.3
  http: ^0.13.4 
  flutter_markdown: ^0.6.9
  timeago: ^3.2.1
  intl: ^0.17.0
  uuid: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: any

flutter:
